export const NAME_PAGE = {
  PRODUCT_PAGE: {
    GET_PRODUCTS : "GET_PRODUCTS",
    GET_CATEGORY : "GET_CATEGORY",
    GET_COMPANY  : "GET_COMPANY",
    GET_WEIGHT   : "GET_WEIGHT",
    GET_FILTERRED: "GET_FILTERRED",
    GET_SORTED   : "GET_SORTED",
  },
};
